train: dataset/images/train
val: dataset/images/val

nc: 2  # ÌÅ¥ÎûòÏä§ Í∞úÏàò
names: ['Ï≤†Ï∫î', 'Í±¥Ï†ÑÏßÄ']

yolo task=detect mode=train data=dataset/dataset.yaml model=yolov8n.pt epochs=50 imgsz=640

expected <block end>, but found ']'
  in "<unicode string>", line 5, column 21:
    names: ['Ï≤†Ï∫î', 'Í±¥Ï†ÑÏßÄ']]
                        ^
hgkim@ubuntu:~/Documents/trash_detect$ yolo task=detect mode=train data=dataset/dataset.yaml model=yolov8n.pt epochs=50 imgsz=640
New https://pypi.org/project/ultralytics/8.3.53 available üòÉ Update with 'pip install -U ultralytics'
Ultralytics 8.3.13 üöÄ Python-3.10.16 torch-2.4.1+cu121 CPU (13th Gen Intel Core(TM) i9-13900K)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=dataset/dataset.yaml, epochs=50, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train2
Traceback (most recent call last):
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 557, in get_dataset
    data = check_det_dataset(self.args.data)
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/data/utils.py", line 329, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError: 
Dataset 'dataset/dataset.yaml' images not found ‚ö†Ô∏è, missing path '/home/hgkim/Documents/yolov5-master/datasets/dataset/dataset/images/val'
Note dataset download directory is '/home/hgkim/Documents/yolov5-master/datasets'. You can update this in '/home/hgkim/.config/Ultralytics/settings.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hgkim/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 799, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 796, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 133, in __init__
    self.trainset, self.testset = self.get_dataset()
  File "/home/hgkim/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 561, in get_dataset
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}")) from e
RuntimeError: Dataset 'dataset/dataset.yaml' error ‚ùå 
Dataset 'dataset/dataset.yaml' images not found ‚ö†Ô∏è, missing path '/home/hgkim/Documents/yolov5-master/datasets/dataset/dataset/images/val'
Note dataset download directory is '/home/hgkim/Documents/yolov5-master/datasets'. You can update this in '/home/hgkim/.config/Ultralytics/settings.json'
